In [29]:
pip install matplotlib

Requirement already satisfied: matplotlib in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (3.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (1.24.2)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11 (from matplotlib) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/opt/six/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [30]:
pip install scikit-plot

Requirement already satisfied: scikit-plot in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (0.3.7)
Requirement already satisfied: matplotlib>=1.4.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-plot) (3.7.0)
Requirement already satisfied: scikit-learn>=0.18 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-plot) (1.2.1)
Requirement already satisfied: scipy>=0.9 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-plot) (1.10.1)
Requirement already satisfied: joblib>=0.10 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-plot) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (1.24.2)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11 (from matplotlib>=1.4.0->scikit-plot) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from matplotlib>=1.4.0->scikit-plot) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-learn>=0.18->scikit-plot) (3.1.0)
Requirement already satisfied: six>=1.5 in /opt/homebrew/opt/six/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->scikit-plot) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [31]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (1.2.1)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: scipy>=1.3.2 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/Cellar/jupyterlab/3.6.1/libexec/lib/python3.11/site-packages (from scikit-learn) (3.1.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import pandas as pd
import math

In [33]:
df = pd.read_csv('/Users/navtegh/Downloads/Final_data/modelling_set.csv')
df.describe()

,MemberID,LabCount_total,LabCount_max,LabCount_min,LabCount_ave,LabCount_months,LabCount_std,DrugCount_total,DrugCount_max,DrugCount_min,...,ProcedureGroup_Count_SO,ProcedureGroup_Count_SMCD,AgeAtFirstClaim,Male,Female,MissSex,MissAge,ClaimsTruncated,TARGET,trainset
count,2.184150e+05,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,...,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.000000,218415.0,218415.000000,147473.000000,218415.000000
mean,4.993458e+07,6.471827,3.829439,2.181860,2.918800,1.655033,0.578166,10.387318,2.193531,0.962237,...,0.001699,0.015457,47.750155,0.363524,0.448078,0.188398,0.0,0.054863,0.452951,0.675196
std,2.892479e+07,7.734678,3.440373,2.507408,2.676663,1.906704,1.683426,15.721582,2.271990,1.057978,...,0.047286,0.262061,23.238375,0.481015,0.497298,0.391031,0.0,0.227714,1.573818,0.468303
min,4.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
25%,2.478774e+07,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,35.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
50%,4.993677e+07,4.000000,4.000000,1.000000,2.666667,1.000000,0.000000,3.000000,2.000000,1.000000,...,0.000000,0.000000,45.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000
75%,7.515525e+07,10.000000,7.000000,3.000000,5.000000,2.000000,1.527525,14.000000,4.000000,1.000000,...,0.000000,0.000000,65.000000,1.000000,1.000000,0.000000,0.0,0.000000,0.000000,1.000000
max,9.999882e+07,111.000000,10.000000,10.000000,10.000000,12.000000,6.363961,84.000000,7.000000,7.000000,...,4.000000,23.000000,80.000000,1.000000,1.000000,1.000000,0.0,1.000000,15.000000,1.000000

In [34]:
df_train = df[df['trainset']==1]

In [35]:
df_train.head

<bound method NDFrame.head of        Year  MemberID  LabCount_total  LabCount_max  LabCount_min  \
0        Y1       210             2.0           2.0           2.0
1        Y2       210             1.0           1.0           1.0
3        Y1      3889            10.0          10.0          10.0
4        Y1     11951             3.0           3.0           3.0
5        Y2     11951             3.0           3.0           3.0
...     ...       ...             ...           ...           ...
214060   Y2  99886482             0.0           0.0           0.0
214061   Y2  99908549             0.0           0.0           0.0
214062   Y2  99910963             0.0           0.0           0.0
214063   Y2  99944120             0.0           0.0           0.0
214064   Y2  99954127             0.0           0.0           0.0

        LabCount_ave  LabCount_months  LabCount_std  DrugCount_total  \
0                2.0              1.0          -1.0              5.0
1                1.0              1.0          -1.0              0.0
3               10.0              1.0          -1.0             30.0
4                3.0              1.0          -1.0              0.0
5                3.0              1.0          -1.0              0.0
...              ...              ...           ...              ...
214060           0.0              0.0           0.0              0.0
214061           0.0              0.0           0.0              0.0
214062           0.0              0.0           0.0              0.0
214063           0.0              0.0           0.0              0.0
214064           0.0              0.0           0.0              0.0

        DrugCount_max  ...  ProcedureGroup_Count_SO  \
0                 2.0  ...                        0
1                 0.0  ...                        0
3                 5.0  ...                        0
4                 0.0  ...                        0
5                 0.0  ...                        0
...               ...  ...                      ...
214060            0.0  ...                        0
214061            0.0  ...                        0
214062            0.0  ...                        0
214063            0.0  ...                        0
214064            0.0  ...                        0

        ProcedureGroup_Count_SMCD  AgeAtFirstClaim  Male  Female  MissSex  \
0                               0               35     0       0        1
1                               0               35     0       0        1
3                               0               45     0       1        0
4                               0               15     0       1        0
5                               0               15     0       1        0
...                           ...              ...   ...     ...      ...
214060                          0               25     0       1        0
214061                          0               65     0       1        0
214062                          0               15     0       1        0
214063                          0               45     1       0        0
214064                          0               15     1       0        0

        MissAge  ClaimsTruncated  TARGET  trainset
0             0                0     0.0         1
1             0                0     0.0         1
3             0                0     0.0         1
4             0                0     1.0         1
5             0                0     0.0         1
...         ...              ...     ...       ...
214060        0                0     0.0         1
214061        0                0     0.0         1
214062        0                1     0.0         1
214063        0                0     0.0         1
214064        0                0     0.0         1

[147473 rows x 145 columns]>

In [36]:
a=df_train['TARGET']

In [37]:
df_train.drop('TARGET',axis=1)
df_train.drop('trainset',axis=1)

,Year,MemberID,LabCount_total,LabCount_max,LabCount_min,LabCount_ave,LabCount_months,LabCount_std,DrugCount_total,DrugCount_max,...,ProcedureGroup_Count_SUS,ProcedureGroup_Count_SO,ProcedureGroup_Count_SMCD,AgeAtFirstClaim,Male,Female,MissSex,MissAge,ClaimsTruncated,TARGET
0,Y1,210,2.0,2.0,2.0,2.0,1.0,-1.0,5.0,2.0,...,0,0,0,35,0,0,1,0,0,0.0
1,Y2,210,1.0,1.0,1.0,1.0,1.0,-1.0,0.0,0.0,...,0,0,0,35,0,0,1,0,0,0.0
3,Y1,3889,10.0,10.0,10.0,10.0,1.0,-1.0,30.0,5.0,...,0,0,0,45,0,1,0,0,0,0.0
4,Y1,11951,3.0,3.0,3.0,3.0,1.0,-1.0,0.0,0.0,...,0,0,0,15,0,1,0,0,0,1.0
5,Y2,11951,3.0,3.0,3.0,3.0,1.0,-1.0,0.0,0.0,...,0,0,0,15,0,1,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214060,Y2,99886482,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,25,0,1,0,0,0,0.0
214061,Y2,99908549,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,65,0,1,0,0,0,0.0
214062,Y2,99910963,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,15,0,1,0,0,1,0.0
214063,Y2,99944120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,45,1,0,0,0,0,0.0
214064,Y2,99954127,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,15,1,0,0,0,0,0.0

In [38]:
from sklearn.model_selection import StratifiedShuffleSplit

# Set the split ratio
train_size = 0.8
test_size = 0.2

# Initialize the StratifiedShuffleSplit object
stratified_split = StratifiedShuffleSplit(n_splits=1, train_size=train_size, test_size=test_size, random_state=42)

# Use the split function to generate indices for the train/test split
train_idx, test_idx = next(stratified_split.split(X=df_train, y=a))

# Use the indices to split the dataset into train and test sets
X_train, y_train = df_train.iloc[train_idx], a.iloc[train_idx]
X_test, y_test = df_train.iloc[test_idx], a.iloc[test_idx]

In [39]:
from sklearn.model_selection import StratifiedShuffleSplit
for x, y in stratified_split.split(df_train, a):
    stratified_random_sample = df_train.iloc[y]

# View sampled data frame
stratified_random_sample

,Year,MemberID,LabCount_total,LabCount_max,LabCount_min,LabCount_ave,LabCount_months,LabCount_std,DrugCount_total,DrugCount_max,...,ProcedureGroup_Count_SO,ProcedureGroup_Count_SMCD,AgeAtFirstClaim,Male,Female,MissSex,MissAge,ClaimsTruncated,TARGET,trainset
3335,Y1,2709359,3.0,2.0,1.0,1.500000,2.0,0.707107,11.0,2.0,...,0,0,80,1,0,0,0,0,0.0,1
11962,Y2,9540207,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0,0,15,1,0,0,0,0,0.0,1
77340,Y1,62463612,26.0,6.0,1.0,2.166667,12.0,1.850471,39.0,4.0,...,0,0,55,0,0,1,0,1,0.0,1
127887,Y2,9946251,10.0,10.0,10.0,10.000000,1.0,-1.000000,21.0,5.0,...,0,0,45,1,0,0,0,0,0.0,1
38871,Y1,31301603,16.0,8.0,1.0,4.000000,4.0,2.943920,13.0,3.0,...,0,0,35,0,1,0,0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190397,Y2,76506874,0.0,0.0,0.0,0.000000,0.0,0.000000,7.0,3.0,...,0,0,75,1,0,0,0,0,0.0,1
20020,Y1,16029814,10.0,10.0,10.0,10.000000,1.0,-1.000000,7.0,2.0,...,0,3,25,0,1,0,0,0,0.0,1
80558,Y1,65010996,10.0,10.0,10.0,10.000000,1.0,-1.000000,1.0,1.0,...,0,0,45,0,0,1,0,0,1.0,1
57895,Y1,46623255,5.0,5.0,5.0,5.000000,1.0,-1.000000,10.0,2.0,...,0,0,35,1,0,0,0,0,0.0,1
120886,Y2,97423937,7.0,7.0,7.0,7.000000,1.0,-1.000000,23.0,4.0,...,0,0,75,0,1,0,0,0,1.0,1

In [40]:
df_train=stratified_random_sample

In [41]:
#Count missing data
def count_missing(df):   
    total = df.isnull().sum().sort_values(ascending=False)
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
    missing_data  = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    print(missing_data.head(20))
    return missing_data

count_missing(df_train)

                                     Total  Percent
Year                                     0      0.0
PrimaryConditionGroup_Count_NEUMENT      0      0.0
PrimaryConditionGroup_Count_HIPFX        0      0.0
PrimaryConditionGroup_Count_SKNAUT       0      0.0
PrimaryConditionGroup_Count_CANCRB       0      0.0
PrimaryConditionGroup_Count_SEIZURE      0      0.0
PrimaryConditionGroup_Count_CHF          0      0.0
PrimaryConditionGroup_Count_PRGNCY       0      0.0
PrimaryConditionGroup_Count_METAB1       0      0.0
PrimaryConditionGroup_Count_HEART4       0      0.0
PrimaryConditionGroup_Count_ODaBNCA      0      0.0
PrimaryConditionGroup_Count_HEMTOL       0      0.0
PrimaryConditionGroup_Count_GYNECA       0      0.0
PrimaryConditionGroup_Count_APPCHOL      0      0.0
PrimaryConditionGroup_Count_MISCL1       0      0.0
PrimaryConditionGroup_Count_RENAL2       0      0.0
PrimaryConditionGroup_Count_Unknown      0      0.0
PrimaryConditionGroup_Count_GIBLEED      0      0.0
PrimaryConditionGroup_Count_COPD         0      0.0
PrimaryConditionGroup_Count_UTI          0      0.0

                                     Total  Percent
Year                                     0      0.0
PrimaryConditionGroup_Count_NEUMENT      0      0.0
PrimaryConditionGroup_Count_HIPFX        0      0.0
PrimaryConditionGroup_Count_SKNAUT       0      0.0
PrimaryConditionGroup_Count_CANCRB       0      0.0
...                                    ...      ...
DSFS_range                               0      0.0
CharlsonIndex_range                      0      0.0
Specialty_Count_Surgery                  0      0.0
Specialty_Count_Internal                 0      0.0
trainset                                 0      0.0

[145 rows x 2 columns]

In [42]:
df_target = df[df['trainset']==0]

In [43]:
m = (df_train.columns != 'TARGET') & (df_train.columns != 'MemberID') & (df_train.columns != 'Year') & (df_train.columns != 'trainset')
X = df_train.loc[:, m]
y = df_train['TARGET']
y.describe()

count    29495.000000
mean         0.452924
std          1.573738
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         15.000000
Name: TARGET, dtype: float64

In [44]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler(feature_range=(0,1)).fit(X)
X = scaler.transform(X)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

In [46]:
def eval(model, X_test, y_test):
    y_pred = model.predict(X_test) # your predicted y values
    y_pred_int64 = y_pred.round(0).astype(int)
    # The root mean square logarithmic error
    msle = np.mean((np.log(y_pred_int64 + 1) - np.log(y_test + 1)) ** 2)
    rmsle = math.sqrt(msle)
    
    print ("RMSLE: %.4f" % rmsle)
    from sklearn.metrics import r2_score
    r2 = r2_score(y_pred, y_test)
    print ("R2 value: %.4f" % r2)
    return rmsle, r2

In [47]:
from sklearn.utils import class_weight
# class_weights = class_weight.compute_class_weight('balanced',
#                                                  np.unique(y_train),
#                                                  y_train)
class_weights =class_weight.compute_class_weight(
                                        class_weight = "balanced",
                                        classes = np.unique(y_train),
                                        y =y_train                                                   
                                    )
class_weights = np.array(class_weights).tolist()
d = {}

for idx,item in enumerate(class_weights):
    d[idx] = item
d

{0: 0.07379475008578291,
 1: 0.9523062730627306,
 2: 2.08125,
 3: 3.3343023255813953,
 4: 5.1615,
 5: 8.489309210526315,
 6: 14.498595505617978,
 7: 20.162109375,
 8: 33.08653846153846,
 9: 41.625,
 10: 36.86785714285714,
 11: 53.765625,
 12: 61.44642857142857,
 13: 75.90441176470588,
 14: 129.0375,
 15: 19.551136363636363}

In [48]:
hyper_para = {'C': 0.001, 'penalty': 'l1', 'solver': 'saga'}
model = linear_model.LogisticRegression(n_jobs=-1, verbose=1, **hyper_para)
model.fit(X_train, y_train)
#eval(model, X_test, y_test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.

convergence after 4 epochs took 1 seconds

[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    1.1s finished

LogisticRegression(C=0.001, n_jobs=-1, penalty='l1', solver='saga', verbose=1)

In [49]:
eval(model, X_test, y_test)

RMSLE: 0.5195
R2 value: 0.0000

(0.5195217459923236, 0.0)

In [50]:
y_pred = model.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8485704599389762